/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/autoscaling/v1alpha1"
	scheme "github.com/kubewharf/katalyst-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KatalystVerticalPodAutoscalersGetter has a method to return a KatalystVerticalPodAutoscalerInterface.
// A group's client should implement this interface.
type KatalystVerticalPodAutoscalersGetter interface {
	KatalystVerticalPodAutoscalers(namespace string) KatalystVerticalPodAutoscalerInterface
}

// KatalystVerticalPodAutoscalerInterface has methods to work with KatalystVerticalPodAutoscaler resources.
type KatalystVerticalPodAutoscalerInterface interface {
	Create(*v1alpha1.KatalystVerticalPodAutoscaler) (*v1alpha1.KatalystVerticalPodAutoscaler, error)
	Update(*v1alpha1.KatalystVerticalPodAutoscaler) (*v1alpha1.KatalystVerticalPodAutoscaler, error)
	UpdateStatus(*v1alpha1.KatalystVerticalPodAutoscaler) (*v1alpha1.KatalystVerticalPodAutoscaler, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KatalystVerticalPodAutoscaler, error)
	List(opts v1.ListOptions) (*v1alpha1.KatalystVerticalPodAutoscalerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KatalystVerticalPodAutoscaler, err error)
	KatalystVerticalPodAutoscalerExpansion
}

// katalystVerticalPodAutoscalers implements KatalystVerticalPodAutoscalerInterface
type katalystVerticalPodAutoscalers struct {
	client rest.Interface
	ns     string
}

// newKatalystVerticalPodAutoscalers returns a KatalystVerticalPodAutoscalers
func newKatalystVerticalPodAutoscalers(c *AutoscalingV1alpha1Client, namespace string) *katalystVerticalPodAutoscalers {
	return &katalystVerticalPodAutoscalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the katalystVerticalPodAutoscaler, and returns the corresponding katalystVerticalPodAutoscaler object, and an error if there is any.
func (c *katalystVerticalPodAutoscalers) Get(name string, options v1.GetOptions) (result *v1alpha1.KatalystVerticalPodAutoscaler, err error) {
	result = &v1alpha1.KatalystVerticalPodAutoscaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KatalystVerticalPodAutoscalers that match those selectors.
func (c *katalystVerticalPodAutoscalers) List(opts v1.ListOptions) (result *v1alpha1.KatalystVerticalPodAutoscalerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KatalystVerticalPodAutoscalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested katalystVerticalPodAutoscalers.
func (c *katalystVerticalPodAutoscalers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a katalystVerticalPodAutoscaler and creates it.  Returns the server's representation of the katalystVerticalPodAutoscaler, and an error, if there is any.
func (c *katalystVerticalPodAutoscalers) Create(katalystVerticalPodAutoscaler *v1alpha1.KatalystVerticalPodAutoscaler) (result *v1alpha1.KatalystVerticalPodAutoscaler, err error) {
	result = &v1alpha1.KatalystVerticalPodAutoscaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		Body(katalystVerticalPodAutoscaler).
		Do().
		Into(result)
	return
}

// Update takes the representation of a katalystVerticalPodAutoscaler and updates it. Returns the server's representation of the katalystVerticalPodAutoscaler, and an error, if there is any.
func (c *katalystVerticalPodAutoscalers) Update(katalystVerticalPodAutoscaler *v1alpha1.KatalystVerticalPodAutoscaler) (result *v1alpha1.KatalystVerticalPodAutoscaler, err error) {
	result = &v1alpha1.KatalystVerticalPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		Name(katalystVerticalPodAutoscaler.Name).
		Body(katalystVerticalPodAutoscaler).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *katalystVerticalPodAutoscalers) UpdateStatus(katalystVerticalPodAutoscaler *v1alpha1.KatalystVerticalPodAutoscaler) (result *v1alpha1.KatalystVerticalPodAutoscaler, err error) {
	result = &v1alpha1.KatalystVerticalPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		Name(katalystVerticalPodAutoscaler.Name).
		SubResource("status").
		Body(katalystVerticalPodAutoscaler).
		Do().
		Into(result)
	return
}

// Delete takes name of the katalystVerticalPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *katalystVerticalPodAutoscalers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *katalystVerticalPodAutoscalers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched katalystVerticalPodAutoscaler.
func (c *katalystVerticalPodAutoscalers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KatalystVerticalPodAutoscaler, err error) {
	result = &v1alpha1.KatalystVerticalPodAutoscaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("katalystverticalpodautoscalers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
