/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	scheme "github.com/kubewharf/katalyst-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomNodeConfigsGetter has a method to return a CustomNodeConfigInterface.
// A group's client should implement this interface.
type CustomNodeConfigsGetter interface {
	CustomNodeConfigs() CustomNodeConfigInterface
}

// CustomNodeConfigInterface has methods to work with CustomNodeConfig resources.
type CustomNodeConfigInterface interface {
	Create(*v1alpha1.CustomNodeConfig) (*v1alpha1.CustomNodeConfig, error)
	Update(*v1alpha1.CustomNodeConfig) (*v1alpha1.CustomNodeConfig, error)
	UpdateStatus(*v1alpha1.CustomNodeConfig) (*v1alpha1.CustomNodeConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CustomNodeConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.CustomNodeConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomNodeConfig, err error)
	CustomNodeConfigExpansion
}

// customNodeConfigs implements CustomNodeConfigInterface
type customNodeConfigs struct {
	client rest.Interface
}

// newCustomNodeConfigs returns a CustomNodeConfigs
func newCustomNodeConfigs(c *ConfigV1alpha1Client) *customNodeConfigs {
	return &customNodeConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the customNodeConfig, and returns the corresponding customNodeConfig object, and an error if there is any.
func (c *customNodeConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.CustomNodeConfig, err error) {
	result = &v1alpha1.CustomNodeConfig{}
	err = c.client.Get().
		Resource("customnodeconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomNodeConfigs that match those selectors.
func (c *customNodeConfigs) List(opts v1.ListOptions) (result *v1alpha1.CustomNodeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CustomNodeConfigList{}
	err = c.client.Get().
		Resource("customnodeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customNodeConfigs.
func (c *customNodeConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("customnodeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a customNodeConfig and creates it.  Returns the server's representation of the customNodeConfig, and an error, if there is any.
func (c *customNodeConfigs) Create(customNodeConfig *v1alpha1.CustomNodeConfig) (result *v1alpha1.CustomNodeConfig, err error) {
	result = &v1alpha1.CustomNodeConfig{}
	err = c.client.Post().
		Resource("customnodeconfigs").
		Body(customNodeConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a customNodeConfig and updates it. Returns the server's representation of the customNodeConfig, and an error, if there is any.
func (c *customNodeConfigs) Update(customNodeConfig *v1alpha1.CustomNodeConfig) (result *v1alpha1.CustomNodeConfig, err error) {
	result = &v1alpha1.CustomNodeConfig{}
	err = c.client.Put().
		Resource("customnodeconfigs").
		Name(customNodeConfig.Name).
		Body(customNodeConfig).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *customNodeConfigs) UpdateStatus(customNodeConfig *v1alpha1.CustomNodeConfig) (result *v1alpha1.CustomNodeConfig, err error) {
	result = &v1alpha1.CustomNodeConfig{}
	err = c.client.Put().
		Resource("customnodeconfigs").
		Name(customNodeConfig.Name).
		SubResource("status").
		Body(customNodeConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the customNodeConfig and deletes it. Returns an error if one occurs.
func (c *customNodeConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("customnodeconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customNodeConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("customnodeconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched customNodeConfig.
func (c *customNodeConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomNodeConfig, err error) {
	result = &v1alpha1.CustomNodeConfig{}
	err = c.client.Patch(pt).
		Resource("customnodeconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
