/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	scheme "github.com/kubewharf/katalyst-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KatalystCustomConfigsGetter has a method to return a KatalystCustomConfigInterface.
// A group's client should implement this interface.
type KatalystCustomConfigsGetter interface {
	KatalystCustomConfigs(namespace string) KatalystCustomConfigInterface
}

// KatalystCustomConfigInterface has methods to work with KatalystCustomConfig resources.
type KatalystCustomConfigInterface interface {
	Create(*v1alpha1.KatalystCustomConfig) (*v1alpha1.KatalystCustomConfig, error)
	Update(*v1alpha1.KatalystCustomConfig) (*v1alpha1.KatalystCustomConfig, error)
	UpdateStatus(*v1alpha1.KatalystCustomConfig) (*v1alpha1.KatalystCustomConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KatalystCustomConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.KatalystCustomConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KatalystCustomConfig, err error)
	KatalystCustomConfigExpansion
}

// katalystCustomConfigs implements KatalystCustomConfigInterface
type katalystCustomConfigs struct {
	client rest.Interface
	ns     string
}

// newKatalystCustomConfigs returns a KatalystCustomConfigs
func newKatalystCustomConfigs(c *ConfigV1alpha1Client, namespace string) *katalystCustomConfigs {
	return &katalystCustomConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the katalystCustomConfig, and returns the corresponding katalystCustomConfig object, and an error if there is any.
func (c *katalystCustomConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.KatalystCustomConfig, err error) {
	result = &v1alpha1.KatalystCustomConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KatalystCustomConfigs that match those selectors.
func (c *katalystCustomConfigs) List(opts v1.ListOptions) (result *v1alpha1.KatalystCustomConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KatalystCustomConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested katalystCustomConfigs.
func (c *katalystCustomConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a katalystCustomConfig and creates it.  Returns the server's representation of the katalystCustomConfig, and an error, if there is any.
func (c *katalystCustomConfigs) Create(katalystCustomConfig *v1alpha1.KatalystCustomConfig) (result *v1alpha1.KatalystCustomConfig, err error) {
	result = &v1alpha1.KatalystCustomConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		Body(katalystCustomConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a katalystCustomConfig and updates it. Returns the server's representation of the katalystCustomConfig, and an error, if there is any.
func (c *katalystCustomConfigs) Update(katalystCustomConfig *v1alpha1.KatalystCustomConfig) (result *v1alpha1.KatalystCustomConfig, err error) {
	result = &v1alpha1.KatalystCustomConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		Name(katalystCustomConfig.Name).
		Body(katalystCustomConfig).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *katalystCustomConfigs) UpdateStatus(katalystCustomConfig *v1alpha1.KatalystCustomConfig) (result *v1alpha1.KatalystCustomConfig, err error) {
	result = &v1alpha1.KatalystCustomConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		Name(katalystCustomConfig.Name).
		SubResource("status").
		Body(katalystCustomConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the katalystCustomConfig and deletes it. Returns an error if one occurs.
func (c *katalystCustomConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *katalystCustomConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched katalystCustomConfig.
func (c *katalystCustomConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KatalystCustomConfig, err error) {
	result = &v1alpha1.KatalystCustomConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("katalystcustomconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
