/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/recommendation/v1alpha1"
	scheme "github.com/kubewharf/katalyst-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceRecommendsGetter has a method to return a ResourceRecommendInterface.
// A group's client should implement this interface.
type ResourceRecommendsGetter interface {
	ResourceRecommends(namespace string) ResourceRecommendInterface
}

// ResourceRecommendInterface has methods to work with ResourceRecommend resources.
type ResourceRecommendInterface interface {
	Create(*v1alpha1.ResourceRecommend) (*v1alpha1.ResourceRecommend, error)
	Update(*v1alpha1.ResourceRecommend) (*v1alpha1.ResourceRecommend, error)
	UpdateStatus(*v1alpha1.ResourceRecommend) (*v1alpha1.ResourceRecommend, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ResourceRecommend, error)
	List(opts v1.ListOptions) (*v1alpha1.ResourceRecommendList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceRecommend, err error)
	ResourceRecommendExpansion
}

// resourceRecommends implements ResourceRecommendInterface
type resourceRecommends struct {
	client rest.Interface
	ns     string
}

// newResourceRecommends returns a ResourceRecommends
func newResourceRecommends(c *RecommendationV1alpha1Client, namespace string) *resourceRecommends {
	return &resourceRecommends{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceRecommend, and returns the corresponding resourceRecommend object, and an error if there is any.
func (c *resourceRecommends) Get(name string, options v1.GetOptions) (result *v1alpha1.ResourceRecommend, err error) {
	result = &v1alpha1.ResourceRecommend{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcerecommends").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceRecommends that match those selectors.
func (c *resourceRecommends) List(opts v1.ListOptions) (result *v1alpha1.ResourceRecommendList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ResourceRecommendList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcerecommends").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceRecommends.
func (c *resourceRecommends) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcerecommends").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a resourceRecommend and creates it.  Returns the server's representation of the resourceRecommend, and an error, if there is any.
func (c *resourceRecommends) Create(resourceRecommend *v1alpha1.ResourceRecommend) (result *v1alpha1.ResourceRecommend, err error) {
	result = &v1alpha1.ResourceRecommend{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcerecommends").
		Body(resourceRecommend).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourceRecommend and updates it. Returns the server's representation of the resourceRecommend, and an error, if there is any.
func (c *resourceRecommends) Update(resourceRecommend *v1alpha1.ResourceRecommend) (result *v1alpha1.ResourceRecommend, err error) {
	result = &v1alpha1.ResourceRecommend{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcerecommends").
		Name(resourceRecommend.Name).
		Body(resourceRecommend).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *resourceRecommends) UpdateStatus(resourceRecommend *v1alpha1.ResourceRecommend) (result *v1alpha1.ResourceRecommend, err error) {
	result = &v1alpha1.ResourceRecommend{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcerecommends").
		Name(resourceRecommend.Name).
		SubResource("status").
		Body(resourceRecommend).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourceRecommend and deletes it. Returns an error if one occurs.
func (c *resourceRecommends) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcerecommends").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceRecommends) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcerecommends").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourceRecommend.
func (c *resourceRecommends) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ResourceRecommend, err error) {
	result = &v1alpha1.ResourceRecommend{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcerecommends").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
