/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/resourceportrait/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePortraits implements PortraitInterface
type FakePortraits struct {
	Fake *FakeResourceportraitV1alpha1
	ns   string
}

var portraitsResource = schema.GroupVersionResource{Group: "resourceportrait.halo.io", Version: "v1alpha1", Resource: "portraits"}

var portraitsKind = schema.GroupVersionKind{Group: "resourceportrait.halo.io", Version: "v1alpha1", Kind: "Portrait"}

// Get takes name of the portrait, and returns the corresponding portrait object, and an error if there is any.
func (c *FakePortraits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Portrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(portraitsResource, c.ns, name), &v1alpha1.Portrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Portrait), err
}

// List takes label and field selectors, and returns the list of Portraits that match those selectors.
func (c *FakePortraits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PortraitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(portraitsResource, portraitsKind, c.ns, opts), &v1alpha1.PortraitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PortraitList{ListMeta: obj.(*v1alpha1.PortraitList).ListMeta}
	for _, item := range obj.(*v1alpha1.PortraitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested portraits.
func (c *FakePortraits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(portraitsResource, c.ns, opts))

}

// Create takes the representation of a portrait and creates it.  Returns the server's representation of the portrait, and an error, if there is any.
func (c *FakePortraits) Create(ctx context.Context, portrait *v1alpha1.Portrait, opts v1.CreateOptions) (result *v1alpha1.Portrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(portraitsResource, c.ns, portrait), &v1alpha1.Portrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Portrait), err
}

// Update takes the representation of a portrait and updates it. Returns the server's representation of the portrait, and an error, if there is any.
func (c *FakePortraits) Update(ctx context.Context, portrait *v1alpha1.Portrait, opts v1.UpdateOptions) (result *v1alpha1.Portrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(portraitsResource, c.ns, portrait), &v1alpha1.Portrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Portrait), err
}

// Delete takes name of the portrait and deletes it. Returns an error if one occurs.
func (c *FakePortraits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(portraitsResource, c.ns, name), &v1alpha1.Portrait{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePortraits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(portraitsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PortraitList{})
	return err
}

// Patch applies the patch and returns the patched portrait.
func (c *FakePortraits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Portrait, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(portraitsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Portrait{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Portrait), err
}
