/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/workload/v1alpha1"
	scheme "github.com/kubewharf/katalyst-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceProfileDescriptorsGetter has a method to return a ServiceProfileDescriptorInterface.
// A group's client should implement this interface.
type ServiceProfileDescriptorsGetter interface {
	ServiceProfileDescriptors(namespace string) ServiceProfileDescriptorInterface
}

// ServiceProfileDescriptorInterface has methods to work with ServiceProfileDescriptor resources.
type ServiceProfileDescriptorInterface interface {
	Create(*v1alpha1.ServiceProfileDescriptor) (*v1alpha1.ServiceProfileDescriptor, error)
	Update(*v1alpha1.ServiceProfileDescriptor) (*v1alpha1.ServiceProfileDescriptor, error)
	UpdateStatus(*v1alpha1.ServiceProfileDescriptor) (*v1alpha1.ServiceProfileDescriptor, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ServiceProfileDescriptor, error)
	List(opts v1.ListOptions) (*v1alpha1.ServiceProfileDescriptorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceProfileDescriptor, err error)
	ServiceProfileDescriptorExpansion
}

// serviceProfileDescriptors implements ServiceProfileDescriptorInterface
type serviceProfileDescriptors struct {
	client rest.Interface
	ns     string
}

// newServiceProfileDescriptors returns a ServiceProfileDescriptors
func newServiceProfileDescriptors(c *WorkloadV1alpha1Client, namespace string) *serviceProfileDescriptors {
	return &serviceProfileDescriptors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceProfileDescriptor, and returns the corresponding serviceProfileDescriptor object, and an error if there is any.
func (c *serviceProfileDescriptors) Get(name string, options v1.GetOptions) (result *v1alpha1.ServiceProfileDescriptor, err error) {
	result = &v1alpha1.ServiceProfileDescriptor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceProfileDescriptors that match those selectors.
func (c *serviceProfileDescriptors) List(opts v1.ListOptions) (result *v1alpha1.ServiceProfileDescriptorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ServiceProfileDescriptorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceProfileDescriptors.
func (c *serviceProfileDescriptors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a serviceProfileDescriptor and creates it.  Returns the server's representation of the serviceProfileDescriptor, and an error, if there is any.
func (c *serviceProfileDescriptors) Create(serviceProfileDescriptor *v1alpha1.ServiceProfileDescriptor) (result *v1alpha1.ServiceProfileDescriptor, err error) {
	result = &v1alpha1.ServiceProfileDescriptor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		Body(serviceProfileDescriptor).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceProfileDescriptor and updates it. Returns the server's representation of the serviceProfileDescriptor, and an error, if there is any.
func (c *serviceProfileDescriptors) Update(serviceProfileDescriptor *v1alpha1.ServiceProfileDescriptor) (result *v1alpha1.ServiceProfileDescriptor, err error) {
	result = &v1alpha1.ServiceProfileDescriptor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		Name(serviceProfileDescriptor.Name).
		Body(serviceProfileDescriptor).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *serviceProfileDescriptors) UpdateStatus(serviceProfileDescriptor *v1alpha1.ServiceProfileDescriptor) (result *v1alpha1.ServiceProfileDescriptor, err error) {
	result = &v1alpha1.ServiceProfileDescriptor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		Name(serviceProfileDescriptor.Name).
		SubResource("status").
		Body(serviceProfileDescriptor).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceProfileDescriptor and deletes it. Returns an error if one occurs.
func (c *serviceProfileDescriptors) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceProfileDescriptors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceProfileDescriptor.
func (c *serviceProfileDescriptors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceProfileDescriptor, err error) {
	result = &v1alpha1.ServiceProfileDescriptor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("serviceprofiledescriptors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
