package consts

const (
	// Usage5MinAvgKey ...
	Usage5MinAvgKey = "avg_5min"
	// Usage15MinAvgKey ...
	Usage15MinAvgKey = "avg_15min"
	// Usage1HourMaxKey ...
	Usage1HourMaxKey = "max_1hour"
	// Usage1DayMaxKey ...
	Usage1DayMaxKey = "max_1day"
	// Annotation15MinAvgKey ...
	Annotation15MinAvgKey = "avg_15min_metadata"
	// Annotation1HourMaxKey ...
	Annotation1HourMaxKey = "max_1hour_metadata"
	// Annotation1DayMaxKey ...
	Annotation1DayMaxKey = "max_1day_metadata"
)
