/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/node/v1alpha1"
	scheme "github.com/kubewharf/katalyst-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomNodeResourcesGetter has a method to return a CustomNodeResourceInterface.
// A group's client should implement this interface.
type CustomNodeResourcesGetter interface {
	CustomNodeResources() CustomNodeResourceInterface
}

// CustomNodeResourceInterface has methods to work with CustomNodeResource resources.
type CustomNodeResourceInterface interface {
	Create(*v1alpha1.CustomNodeResource) (*v1alpha1.CustomNodeResource, error)
	Update(*v1alpha1.CustomNodeResource) (*v1alpha1.CustomNodeResource, error)
	UpdateStatus(*v1alpha1.CustomNodeResource) (*v1alpha1.CustomNodeResource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CustomNodeResource, error)
	List(opts v1.ListOptions) (*v1alpha1.CustomNodeResourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomNodeResource, err error)
	CustomNodeResourceExpansion
}

// customNodeResources implements CustomNodeResourceInterface
type customNodeResources struct {
	client rest.Interface
}

// newCustomNodeResources returns a CustomNodeResources
func newCustomNodeResources(c *NodeV1alpha1Client) *customNodeResources {
	return &customNodeResources{
		client: c.RESTClient(),
	}
}

// Get takes name of the customNodeResource, and returns the corresponding customNodeResource object, and an error if there is any.
func (c *customNodeResources) Get(name string, options v1.GetOptions) (result *v1alpha1.CustomNodeResource, err error) {
	result = &v1alpha1.CustomNodeResource{}
	err = c.client.Get().
		Resource("customnoderesources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomNodeResources that match those selectors.
func (c *customNodeResources) List(opts v1.ListOptions) (result *v1alpha1.CustomNodeResourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CustomNodeResourceList{}
	err = c.client.Get().
		Resource("customnoderesources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customNodeResources.
func (c *customNodeResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("customnoderesources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a customNodeResource and creates it.  Returns the server's representation of the customNodeResource, and an error, if there is any.
func (c *customNodeResources) Create(customNodeResource *v1alpha1.CustomNodeResource) (result *v1alpha1.CustomNodeResource, err error) {
	result = &v1alpha1.CustomNodeResource{}
	err = c.client.Post().
		Resource("customnoderesources").
		Body(customNodeResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a customNodeResource and updates it. Returns the server's representation of the customNodeResource, and an error, if there is any.
func (c *customNodeResources) Update(customNodeResource *v1alpha1.CustomNodeResource) (result *v1alpha1.CustomNodeResource, err error) {
	result = &v1alpha1.CustomNodeResource{}
	err = c.client.Put().
		Resource("customnoderesources").
		Name(customNodeResource.Name).
		Body(customNodeResource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *customNodeResources) UpdateStatus(customNodeResource *v1alpha1.CustomNodeResource) (result *v1alpha1.CustomNodeResource, err error) {
	result = &v1alpha1.CustomNodeResource{}
	err = c.client.Put().
		Resource("customnoderesources").
		Name(customNodeResource.Name).
		SubResource("status").
		Body(customNodeResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the customNodeResource and deletes it. Returns an error if one occurs.
func (c *customNodeResources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("customnoderesources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customNodeResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("customnoderesources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched customNodeResource.
func (c *customNodeResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomNodeResource, err error) {
	result = &v1alpha1.CustomNodeResource{}
	err = c.client.Patch(pt).
		Resource("customnoderesources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
