/*
Copyright 2022 The Katalyst Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubewharf/katalyst-api/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHaloCustomConfigs implements HaloCustomConfigInterface
type FakeHaloCustomConfigs struct {
	Fake *FakeConfigV1alpha1
	ns   string
}

var halocustomconfigsResource = schema.GroupVersionResource{Group: "config.halo.io", Version: "v1alpha1", Resource: "halocustomconfigs"}

var halocustomconfigsKind = schema.GroupVersionKind{Group: "config.halo.io", Version: "v1alpha1", Kind: "HaloCustomConfig"}

// Get takes name of the haloCustomConfig, and returns the corresponding haloCustomConfig object, and an error if there is any.
func (c *FakeHaloCustomConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HaloCustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(halocustomconfigsResource, c.ns, name), &v1alpha1.HaloCustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HaloCustomConfig), err
}

// List takes label and field selectors, and returns the list of HaloCustomConfigs that match those selectors.
func (c *FakeHaloCustomConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HaloCustomConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(halocustomconfigsResource, halocustomconfigsKind, c.ns, opts), &v1alpha1.HaloCustomConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HaloCustomConfigList{ListMeta: obj.(*v1alpha1.HaloCustomConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.HaloCustomConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested haloCustomConfigs.
func (c *FakeHaloCustomConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(halocustomconfigsResource, c.ns, opts))

}

// Create takes the representation of a haloCustomConfig and creates it.  Returns the server's representation of the haloCustomConfig, and an error, if there is any.
func (c *FakeHaloCustomConfigs) Create(ctx context.Context, haloCustomConfig *v1alpha1.HaloCustomConfig, opts v1.CreateOptions) (result *v1alpha1.HaloCustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(halocustomconfigsResource, c.ns, haloCustomConfig), &v1alpha1.HaloCustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HaloCustomConfig), err
}

// Update takes the representation of a haloCustomConfig and updates it. Returns the server's representation of the haloCustomConfig, and an error, if there is any.
func (c *FakeHaloCustomConfigs) Update(ctx context.Context, haloCustomConfig *v1alpha1.HaloCustomConfig, opts v1.UpdateOptions) (result *v1alpha1.HaloCustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(halocustomconfigsResource, c.ns, haloCustomConfig), &v1alpha1.HaloCustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HaloCustomConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHaloCustomConfigs) UpdateStatus(ctx context.Context, haloCustomConfig *v1alpha1.HaloCustomConfig, opts v1.UpdateOptions) (*v1alpha1.HaloCustomConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(halocustomconfigsResource, "status", c.ns, haloCustomConfig), &v1alpha1.HaloCustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HaloCustomConfig), err
}

// Delete takes name of the haloCustomConfig and deletes it. Returns an error if one occurs.
func (c *FakeHaloCustomConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(halocustomconfigsResource, c.ns, name), &v1alpha1.HaloCustomConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHaloCustomConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(halocustomconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HaloCustomConfigList{})
	return err
}

// Patch applies the patch and returns the patched haloCustomConfig.
func (c *FakeHaloCustomConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HaloCustomConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(halocustomconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HaloCustomConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HaloCustomConfig), err
}
